export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const SEARCH_MOVIE_PENDING = 'SEARCH_MOVIE_PENDING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAIL = 'SEARCH_MOVIE_FAIL';

export const NOMINATE_MOVIE = 'NOMINATE_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';